### ISSUE TITLE
Minha ideia

### ISSUE THREAD

**Issue by Jnfagundes** [carolinaclh/Avaliacao#2]
eleitores = [ ]                    #criação de uma lista de eleitores
n = 111 #Variável com o primeiro eleitor
for eleit in range(1,21):     #percorrer a lista para criar novos eleitores
   eleitores.append(n)       #acrescenta um novo eleitor na lista
   n = n + 1 
print(eleitores)

**Comment by carolinaclh** [comment]
Muito obrigada, sua ideia já foi implementada no programa<3
